/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/avatar-transformed.glb --transform --types --output src/components/Model.tsx 
Files: public/avatar-transformed.glb [4.59MB] > /home/thaisfreis/Documentos/Workspace/poc-portfolio/frontend/src/components/avatar-transformed-transformed.glb [6.57MB] (-43%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

type GLTFResult = {
  nodes: {
    ['tripo_node_27d75684-9225-4aa5-ab5e-47d34820c9a4']: THREE.SkinnedMesh
    pescoco: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    Materiais: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { scene } = useGLTF('/avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  
  const targetNode = nodes['tripo_node_27d75684-9225-4aa5-ab5e-47d34820c9a4']

  if (!targetNode) {
    console.warn('Expected node not found in GLB file. Available nodes:', Object.keys(nodes))
    return <primitive object={scene} {...props} />
  }

  return (
    <group {...props} dispose={null} rotation-y={-Math.PI / 2}>
      {nodes.pescoco && <primitive object={nodes.pescoco} />}
      {nodes.neutral_bone && <primitive object={nodes.neutral_bone} />}
      {targetNode.skeleton ? (
        <skinnedMesh
          geometry={targetNode.geometry}
          material={materials.Materiais}
          skeleton={targetNode.skeleton}
        />
      ) : (
        <mesh
          geometry={targetNode.geometry}
          material={materials.Materiais}
        />
      )}
    </group>
  )
}

useGLTF.preload('/avatar.glb')
