openapi: 3.0.0
info:
  title: AI Avatar Chat API
  version: 1.0.0
paths:
  /api/chat:
    post:
      summary: Send a message to the AI avatar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: The AI's response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
